# Generated by Django 4.2.7 on 2023-11-02 14:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('route_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('st_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('sub_dist', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('train_type', models.CharField(max_length=255)),
                ('manufacture_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900)])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='departure_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='railway.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='terminal_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='railway.station'),
        ),
        migrations.AddField(
            model_name='route',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.train'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('rev_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('rev_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_from_station', to='railway.station')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='railway.ticket')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations_to_station', to='railway.station')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
